# Generated by Django 3.1.6 on 2021-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210605_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='nama',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
