# Generated by Django 3.1.6 on 2021-06-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210605_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tugas',
            old_name='judul',
            new_name='judul_pi',
        ),
    ]
