# Generated by Django 3.1.6 on 2021-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210605_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tugas',
            old_name='keterangan',
            new_name='keterangan_Sidang',
        ),
        migrations.RemoveField(
            model_name='tugas',
            name='judul_pi',
        ),
        migrations.AddField(
            model_name='tugas',
            name='judul_PI',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
