# Generated by Django 3.1.6 on 2021-06-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210605_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tugas',
            new_name='PenulisanIlmiah',
        ),
    ]
